### ISSUE TITLE
Error with previous and next line macro

### ISSUE THREAD

**Issue by Nils31011992** [chigkim/VOCR#1]
If I use the Macros an error like the following appears.

/var/folders/7c/nl8j8s0n5ps7v52bdn7wr0hw0000gn/T/Keyboard-Maestro-Script-03566237-88BA-4120-87E1-55AA130441F9:150:190: execution error: Error on line 5: SyntaxError: JSON Parse error: Unexpected identifier "OCR" (-2700)

**Comment by chigkim** [comment]
Were you able to execute ocr front window macro successfully before running that macros? What window were you trying to ocr? Can you just try ocr keyboard maestro editor window first?

**Comment by chigkim** [comment]
I updated the Macros. Can you download again, run import macros app, and try again? If it still fails, can you generate the report following the instruction from the end of readme?

**Comment by Nils31011992** [comment]
Now, after Scan, the Following Error appears:
Desktop: 2560,1600,232
App: Kontakt 5: Kontakt 5
Original: 1980, 1324
Enlarged: 2560, 1712
Error: Can't find Tesseract.
OCR Result from /Users/NilsMichalski/Screenshot.hocr
Error: Can't find output file.

/var/folders/7c/nl8j8s0n5ps7v52bdn7wr0hw0000gn/T/Keyboard-Maestro-Script-9CA6D281-C6FD-4568-9B87-F6BED14A4466:2377:2409: execution error: Error on line 73: ReferenceError: Can't find variable: str (-2700)

**Comment by chigkim** [comment]
According to the error, it can't find Tesseract. Run install.command and see if it gets fixed. Tesseract can take a long time over 15 minutes to install depending on the internet speed and system resource. Also examine the terminal output as it compiles and installs.

**Comment by Nils31011992** [comment]
Hey, Now, the Scan works, after running the installation script again, but there is an Error appearing every scan.
Desktop: 2560,1600,232
App: Native Access: 
Original: 1800, 1544
Enlarged: 2328, 1997
OCR Result from /Users/NilsMichalski/Screenshot.hocr
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title></title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name='ocr-system' content='tesseract 4.00.00alpha' />
  <meta name='ocr-capabilities' content='ocr_page ocr_carea ocr_par ocr_line ocrx_word'/>
</head>
<body>
  <div class='ocr_page' id='page_1' title='image "/Users/NilsMichalski/Screenshot.png"; bbox 0 0 2328 1997; ppageno 0'>
   <div class='ocr_carea' id='block_1_1' title="bbox 0 0 7 7">
    <p class='ocr_par' id='par_1_1' lang='eng' title="bbox 0 0 7 7">
     <span class='ocr_line' id='line_1_1' title="bbox 0 0 7 7; baseline 0 -5; x_size 20; x_descenders 5; x_ascenders 5"><span class='ocrx_word' id='word_1_1' title='bbox 0 0 7 7; x_wconf 58'>1</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_2' title="bbox 0 57 2328 161">
    <p class='ocr_par' id='par_1_2' lang='eng' title="bbox 0 57 2328 161">
     <span class='ocr_line' id='line_1_2' title="bbox 0 57 2328 161; baseline 0 0; x_size 52; x_descenders -26; x_ascenders 26"><span class='ocrx_word' id='word_1_2' title='bbox 0 57 2328 161; x_wconf 95'> </span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_3' title="bbox 2227 52 2324 166">
    <p class='ocr_par' id='par_1_3' lang='eng' title="bbox 2227 52 2324 166">
     <span class='ocr_line' id='line_1_3' title="bbox 2227 52 2324 166; baseline 0 1831; x_size 143.75; x_descenders 35.9375; x_ascenders 35.9375"><span class='ocrx_word' id='word_1_3' title='bbox 2227 52 2324 166; x_wconf 95'> </span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_4' title="bbox 0 92 912 432">
    <p class='ocr_par' id='par_1_4' lang='eng' title="bbox 44 92 367 124">
     <span class='ocr_line' id='line_1_4' title="bbox 44 92 367 124; baseline 0 0; x_size 35.083332; x_descenders 5.5; x_ascenders 11.083333"><span class='ocrx_word' id='word_1_4' title='bbox 44 92 194 124; x_wconf 96'>NATIVE</span> <span class='ocrx_word' id='word_1_5' title='bbox 209 92 367 124; x_wconf 93'>ACCESS</span> 
     </span>
    </p>

    <p class='ocr_par' id='par_1_5' lang='eng' title="bbox 42 205 912 235">
     <span class='ocr_line' id='line_1_5' title="bbox 42 205 912 235; baseline -0.001 -1; x_size 34.351353; x_descenders 5.3513513; x_ascenders 11"><span class='ocrx_word' id='word_1_6' title='bbox 42 205 72 235; x_wconf 61'>®</span> <span class='ocrx_word' id='word_1_7' title='bbox 89 208 145 233; x_wconf 95'>Add</span> <span class='ocrx_word' id='word_1_8' title='bbox 158 215 172 233; x_wconf 96'>a</span> <span class='ocrx_word' id='word_1_9' title='bbox 185 208 261 233; x_wconf 96'>serial</span> <span class='ocrx_word' id='word_1_10' title='bbox 561 210 680 232; x_wconf 95'>Software</span> <span class='ocrx_word' id='word_1_11' title='bbox 704 216 712 229; x_wconf 59'>&gt;</span> <span class='ocrx_word' id='word_1_12' title='bbox 742 211 788 233; x_wconf 96'>Not</span> <span class='ocrx_word' id='word_1_13' title='bbox 800 210 912 233; x_wconf 95'>Installed</span> 
     </span>
    </p>

    <p class='ocr_par' id='par_1_6' lang='eng' title="bbox 0 304 898 432">
     <span class='ocr_line' id='line_1_6' title="bbox 43 304 898 339; baseline 0 -1; x_size 39.135212; x_descenders 6.1352115; x_ascenders 12.36338"><span class='ocrx_word' id='word_1_14' title='bbox 43 310 145 329; x_wconf 96'>Software</span> <span class='ocrx_word' id='word_1_15' title='bbox 561 304 650 339; x_wconf 93'>NOT</span> <span class='ocrx_word' id='word_1_16' title='bbox 664 304 898 339; x_wconf 91'>INSTALLED</span> 
     </span>
     <span class='ocr_line' id='line_1_7' title="bbox 0 350 474 432; baseline -0.002 -31; x_size 30.351351; x_descenders 5.3513513; x_ascenders 7"><span class='ocrx_word' id='word_1_17' title='bbox 0 350 10 432; x_wconf 90'>I</span> <span class='ocrx_word' id='word_1_18' title='bbox 44 377 94 401; x_wconf 95'>Not</span> <span class='ocrx_word' id='word_1_19' title='bbox 106 376 228 401; x_wconf 96'>installed</span> <span class='ocrx_word' id='word_1_20' title='bbox 463 380 474 400; x_wconf 96'>3</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_5' title="bbox 43 420 631 491">
    <p class='ocr_par' id='par_1_7' lang='eng' title="bbox 43 420 631 491">
     <span class='ocr_line' id='line_1_8' title="bbox 43 420 631 491; baseline 0.003 -7; x_size 30; x_descenders 5; x_ascenders 7"><span class='ocrx_word' id='word_1_21' title='bbox 43 459 175 484; x_wconf 95'>Available</span> <span class='ocrx_word' id='word_1_22' title='bbox 187 459 303 490; x_wconf 96'>updates</span> <span class='ocrx_word' id='word_1_23' title='bbox 559 420 631 491; x_wconf 62'>9</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_6' title="bbox 45 542 307 573">
    <p class='ocr_par' id='par_1_8' lang='eng' title="bbox 45 542 307 573">
     <span class='ocr_line' id='line_1_9' title="bbox 45 542 307 573; baseline 0 -7; x_size 31; x_descenders 7; x_ascenders 7"><span class='ocrx_word' id='word_1_24' title='bbox 45 542 166 566; x_wconf 95'>Installed</span> <span class='ocrx_word' id='word_1_25' title='bbox 180 542 307 573; x_wconf 96'>products</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_7' title="bbox 554 518 2254 798">
    <p class='ocr_par' id='par_1_9' lang='eng' title="bbox 554 518 2254 798">
     <span class='ocr_line' id='line_1_10' title="bbox 554 518 2254 798; baseline 0.015 -26; x_size 356; x_descenders 89; x_ascenders 89"><span class='ocrx_word' id='word_1_26' title='bbox 554 518 2254 798; x_wconf 95'>  </span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_8' title="bbox 581 832 616 857">
    <p class='ocr_par' id='par_1_10' lang='eng' title="bbox 581 832 616 857">
     <span class='ocr_line' id='line_1_11' title="bbox 581 832 616 857; baseline 0 0; x_size 34; x_descenders 8.5; x_ascenders 8.5"><span class='ocrx_word' id='word_1_27' title='bbox 581 832 616 857; x_wconf 95'>GF</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_9' title="bbox 720 931 1202 963">
    <p class='ocr_par' id='par_1_11' lang='eng' title="bbox 720 931 1202 963">
     <span class='ocr_line' id='line_1_12' title="bbox 720 931 1202 963; baseline 0 -6; x_size 32; x_descenders 6; x_ascenders 7"><span class='ocrx_word' id='word_1_28' title='bbox 720 932 778 957; x_wconf 96'>The</span> <span class='ocrx_word' id='word_1_29' title='bbox 789 934 890 963; x_wconf 96'>output</span> <span class='ocrx_word' id='word_1_30' title='bbox 902 932 931 957; x_wconf 96'>of</span> <span class='ocrx_word' id='word_1_31' title='bbox 941 932 991 957; x_wconf 95'>the</span> <span class='ocrx_word' id='word_1_32' title='bbox 1002 934 1060 957; x_wconf 96'>text</span> <span class='ocrx_word' id='word_1_33' title='bbox 1072 931 1146 963; x_wconf 96'>script</span> <span class='ocrx_word' id='word_1_34' title='bbox 1148 931 1202 957; x_wconf 96'>is:</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_10' title="bbox 580 992 1894 1757">
    <p class='ocr_par' id='par_1_12' lang='eng' title="bbox 580 992 1894 1748">
     <span class='ocr_line' id='line_1_13' title="bbox 580 992 1145 1027; baseline 0 -10; x_size 32.13044; x_descenders 6.496479; x_ascenders 6.8357663"><span class='ocrx_word' id='word_1_35' title='bbox 580 1002 608 1027; x_wconf 79'>o</span> <span class='ocrx_word' id='word_1_36' title='bbox 739 992 879 1023; x_wconf 92'>Desktop:</span> <span class='ocrx_word' id='word_1_37' title='bbox 907 993 1085 1022; x_wconf 91'>2560,1600,</span> <span class='ocrx_word' id='word_1_38' title='bbox 1094 993 1145 1017; x_wconf 96'>232</span> 
     </span>
     <span class='ocr_line' id='line_1_14' title="bbox 738 1028 1202 1059; baseline 0 -6; x_size 31; x_descenders 6; x_ascenders 7"><span class='ocrx_word' id='word_1_39' title='bbox 738 1029 804 1059; x_wconf 96'>App:</span> <span class='ocrx_word' id='word_1_40' title='bbox 832 1028 958 1053; x_wconf 95'>Kontakt</span> <span class='ocrx_word' id='word_1_41' title='bbox 982 1029 1010 1053; x_wconf 96'>5:</span> <span class='ocrx_word' id='word_1_42' title='bbox 1038 1028 1164 1053; x_wconf 96'>Kontakt</span> <span class='ocrx_word' id='word_1_43' title='bbox 1187 1029 1202 1053; x_wconf 96'>5</span> 
     </span>
     <span class='ocr_line' id='line_1_15' title="bbox 739 1064 1110 1096; baseline 0 -7; x_size 30; x_descenders 5; x_ascenders 7"><span class='ocrx_word' id='word_1_44' title='bbox 739 1064 898 1096; x_wconf 95'>Original:</span> <span class='ocrx_word' id='word_1_45' title='bbox 926 1065 1010 1094; x_wconf 96'>1980,</span> <span class='ocrx_word' id='word_1_46' title='bbox 1039 1065 1110 1089; x_wconf 96'>1324</span> 
     </span>
     <span class='ocr_line' id='line_1_16' title="bbox 740 1101 1109 1132; baseline 0 -7; x_size 31; x_descenders 7; x_ascenders 6"><span class='ocrx_word' id='word_1_47' title='bbox 740 1101 898 1132; x_wconf 96'>Enlarged:</span> <span class='ocrx_word' id='word_1_48' title='bbox 925 1102 1010 1130; x_wconf 96'>2560,</span> <span class='ocrx_word' id='word_1_49' title='bbox 1039 1102 1109 1125; x_wconf 96'>1712</span> 
     </span>
     <span class='ocr_line' id='line_1_17' title="bbox 739 1137 1708 1164; baseline 0 -2; x_size 31.566221; x_descenders 6.5662217; x_ascenders 6"><span class='ocrx_word' id='word_1_50' title='bbox 739 1138 793 1162; x_wconf 95'>OCR</span> <span class='ocrx_word' id='word_1_51' title='bbox 813 1137 921 1162; x_wconf 96'>Result</span> <span class='ocrx_word' id='word_1_52' title='bbox 945 1137 1016 1162; x_wconf 96'>from</span> <span class='ocrx_word' id='word_1_53' title='bbox 1037 1137 1627 1164; x_wconf 80'>/Users/N115M1chalsk1/Screenshot</span> <span class='ocrx_word' id='word_1_54' title='bbox 1637 1137 1708 1162; x_wconf 89'>hocr</span> 
     </span>
     <span class='ocr_line' id='line_1_18' title="bbox 738 1173 1426 1204; baseline 0 -6; x_size 31; x_descenders 6; x_ascenders 6"><span class='ocrx_word' id='word_1_55' title='bbox 738 1173 829 1198; x_wconf 92'>&lt;?xml</span> <span class='ocrx_word' id='word_1_56' title='bbox 851 1173 1088 1198; x_wconf 90'>version=&quot;1.0&quot;</span> <span class='ocrx_word' id='word_1_57' title='bbox 1112 1173 1426 1204; x_wconf 88'>encoding=&quot;UTF—8&quot;?</span> 
     </span>
     <span class='ocr_line' id='line_1_19' title="bbox 738 1209 1891 1237; baseline 0 -3; x_size 32.13044; x_descenders 6.496479; x_ascenders 6.8357663"><span class='ocrx_word' id='word_1_58' title='bbox 738 1210 904 1234; x_wconf 95'>&lt;!DOCTYPE</span> <span class='ocrx_word' id='word_1_59' title='bbox 926 1209 997 1234; x_wconf 93'>html</span> <span class='ocrx_word' id='word_1_60' title='bbox 1020 1210 1127 1234; x_wconf 92'>PUBLIC</span> <span class='ocrx_word' id='word_1_61' title='bbox 1150 1210 1371 1237; x_wconf 86'>&quot;—//W3C//DTD</span> <span class='ocrx_word' id='word_1_62' title='bbox 1391 1210 1484 1234; x_wconf 92'>XHTML</span> <span class='ocrx_word' id='word_1_63' title='bbox 1506 1210 1557 1234; x_wconf 77'>1.0</span> <span class='ocrx_word' id='word_1_64' title='bbox 1579 1209 1891 1237; x_wconf 83'>Transitional//EN&quot;</span> 
     </span>
     <span class='ocr_line' id='line_1_20' title="bbox 814 1245 1894 1277; baseline -0.001 -7; x_size 31; x_descenders 7; x_ascenders 6"><span class='ocrx_word' id='word_1_65' title='bbox 814 1246 1029 1277; x_wconf 10'>&quot;http://www.</span> <span class='ocrx_word' id='word_1_66' title='bbox 1036 1247 1085 1270; x_wconf 10'>w3.</span> <span class='ocrx_word' id='word_1_67' title='bbox 1094 1245 1894 1277; x_wconf 45'>org/TR/xhtml1/DTD/xhtmll—transitional.dtd&quot;&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_21' title="bbox 738 1282 1780 1313; baseline 0 -7; x_size 31; x_descenders 7; x_ascenders 6"><span class='ocrx_word' id='word_1_68' title='bbox 738 1282 829 1306; x_wconf 92'>&lt;html</span> <span class='ocrx_word' id='word_1_69' title='bbox 850 1282 1234 1313; x_wconf 42'>xmlns=&quot;http://www.w3.</span> <span class='ocrx_word' id='word_1_70' title='bbox 1244 1282 1517 1313; x_wconf 42'>org/1999/xhtml&quot;</span> <span class='ocrx_word' id='word_1_71' title='bbox 1542 1282 1780 1313; x_wconf 3'>xml:lang=&quot;en&quot;</span> 
     </span>
     <span class='ocr_line' id='line_1_22' title="bbox 741 1318 923 1349; baseline 0 -6; x_size 31; x_descenders 6; x_ascenders 6"><span class='ocrx_word' id='word_1_72' title='bbox 741 1318 923 1349; x_wconf 79'>lang=&quot;en&quot;&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_23' title="bbox 756 1354 867 1379; baseline 0 0; x_size 31.220631; x_descenders 6.2206311; x_ascenders 7"><span class='ocrx_word' id='word_1_73' title='bbox 756 1354 867 1379; x_wconf 96'>&lt;head&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_24' title="bbox 775 1390 1054 1418; baseline -0.004 -3; x_size 31.220631; x_descenders 6.2206311; x_ascenders 7"><span class='ocrx_word' id='word_1_74' title='bbox 775 1390 1054 1418; x_wconf 49'>&lt;title&gt;&lt;/title&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_25' title="bbox 738 1427 1595 1458; baseline 0.002 -9; x_size 31; x_descenders 7; x_ascenders 6"><span class='ocrx_word' id='word_1_75' title='bbox 738 1429 828 1451; x_wconf 92'>&lt;meta</span> <span class='ocrx_word' id='word_1_76' title='bbox 852 1427 1312 1458; x_wconf 91'>http—equiv=&quot;Content—Type&quot;</span> <span class='ocrx_word' id='word_1_77' title='bbox 1337 1427 1595 1454; x_wconf 92'>content=&quot;text/</span> 
     </span>
     <span class='ocr_line' id='line_1_26' title="bbox 740 1463 1147 1492; baseline -0.007 -4; x_size 31.566221; x_descenders 6.5662217; x_ascenders 6"><span class='ocrx_word' id='word_1_78' title='bbox 740 1463 823 1492; x_wconf 92'>html;</span> <span class='ocrx_word' id='word_1_79' title='bbox 833 1463 1088 1488; x_wconf 90'>charset=utf—8&quot;</span> <span class='ocrx_word' id='word_1_80' title='bbox 1112 1464 1147 1490; x_wconf 96'>/&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_27' title="bbox 775 1499 1876 1530; baseline 0.001 -6; x_size 31; x_descenders 6; x_ascenders 6"><span class='ocrx_word' id='word_1_81' title='bbox 775 1501 865 1524; x_wconf 92'>&lt;meta</span> <span class='ocrx_word' id='word_1_82' title='bbox 889 1499 1197 1530; x_wconf 78'>name=‘ocr—system‘</span> <span class='ocrx_word' id='word_1_83' title='bbox 1226 1499 1556 1524; x_wconf 73'>content=‘tesseract</span> <span class='ocrx_word' id='word_1_84' title='bbox 1579 1499 1814 1530; x_wconf 85'>4.00.00alpha‘</span> <span class='ocrx_word' id='word_1_85' title='bbox 1841 1500 1876 1526; x_wconf 95'>/&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_28' title="bbox 775 1535 1837 1566; baseline 0 -6; x_size 31; x_descenders 6; x_ascenders 7"><span class='ocrx_word' id='word_1_86' title='bbox 775 1537 865 1560; x_wconf 93'>&lt;meta</span> <span class='ocrx_word' id='word_1_87' title='bbox 889 1535 1309 1566; x_wconf 85'>name=‘ocr—capabilities‘</span> <span class='ocrx_word' id='word_1_88' title='bbox 1337 1535 1652 1566; x_wconf 21'>content=‘&quot;ocr_page</span> <span class='ocrx_word' id='word_1_89' title='bbox 1673 1542 1837 1565; x_wconf 91'>ocr_carea</span> 
     </span>
     <span class='ocr_line' id='line_1_29' title="bbox 739 1571 1278 1603; baseline -0.002 -7; x_size 28; x_descenders 5; x_ascenders 5"><span class='ocrx_word' id='word_1_90' title='bbox 739 1578 867 1603; x_wconf 90'>ocr_par</span> <span class='ocrx_word' id='word_1_91' title='bbox 888 1571 1035 1601; x_wconf 90'>ocr_line</span> <span class='ocrx_word' id='word_1_92' title='bbox 1057 1572 1278 1601; x_wconf 89'>ocrx_word‘/&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_30' title="bbox 738 1608 867 1635; baseline -0.016 0; x_size 32.566223; x_descenders 6.5662217; x_ascenders 7"><span class='ocrx_word' id='word_1_93' title='bbox 738 1608 867 1635; x_wconf 96'>&lt;/head&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_31' title="bbox 738 1644 848 1675; baseline 0 -6; x_size 31; x_descenders 6; x_ascenders 6"><span class='ocrx_word' id='word_1_94' title='bbox 738 1644 848 1675; x_wconf 95'>&lt;body&gt;</span> 
     </span>
     <span class='ocr_line' id='line_1_32' title="bbox 775 1680 1800 1711; baseline 0.002 -6; x_size 32; x_descenders 6; x_ascenders 7"><span class='ocrx_word' id='word_1_95' title='bbox 775 1680 847 1705; x_wconf 93'>&lt;div</span> <span class='ocrx_word' id='word_1_96' title='bbox 870 1680 1159 1711; x_wconf 70'>class=‘ocr_page‘</span> <span class='ocrx_word' id='word_1_97' title='bbox 1188 1680 1384 1711; x_wconf 39'>id=‘&quot;page_1‘</span> <span class='ocrx_word' id='word_1_98' title='bbox 1411 1680 1633 1711; x_wconf 46'>title=‘image</span> <span class='ocrx_word' id='word_1_99' title='bbox 1655 1680 1800 1707; x_wconf 89'>&quot;/Users/</span> 
     </span>
     <span class='ocr_line' id='line_1_33' title="bbox 737 1716 1894 1757; baseline 0 -16; x_size 31; x_descenders 6; x_ascenders 7"><span class='ocrx_word' id='word_1_100' title='bbox 737 1716 1197 1744; x_wconf 76'>N115M1chalsk1/Screenshot</span> <span class='ocrx_word' id='word_1_101' title='bbox 1207 1717 1291 1748; x_wconf 91'>png&quot;,</span> <span class='ocrx_word' id='word_1_102' title='bbox 1319 1716 1390 1741; x_wconf 92'>bbox</span> <span class='ocrx_word' id='word_1_103' title='bbox 1412 1717 1427 1741; x_wconf 80'>0</span> <span class='ocrx_word' id='word_1_104' title='bbox 1449 1717 1464 1741; x_wconf 83'>0</span> <span class='ocrx_word' id='word_1_105' title='bbox 1486 1717 1557 1741; x_wconf 78'>2560</span> <span class='ocrx_word' id='word_1_106' title='bbox 1581 1717 1665 1745; x_wconf 92'>1712</span> <span class='ocrx_word' id='word_1_107' title='bbox 1692 1723 1819 1757; x_wconf 92'>ppageno</span> <span class='ocrx_word' id='word_1_108' title='bbox 1842 1716 1869 1741; x_wconf 79'>0</span> <span class='ocrx_word' id='word_1_109' title='bbox 1878 1723 1894 1738; x_wconf 96'>&gt;</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_11' title="bbox 668 927 670 1699">
    <p class='ocr_par' id='par_1_13' lang='eng' title="bbox 668 927 670 1699">
     <span class='ocr_line' id='line_1_34' title="bbox 668 927 670 1699; baseline 0 0; x_size 386; x_descenders -193; x_ascenders 193"><span class='ocrx_word' id='word_1_110' title='bbox 668 927 670 1699; x_wconf 95'> </span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_12' title="bbox 1902 1825 1947 1850">
    <p class='ocr_par' id='par_1_14' lang='eng' title="bbox 1902 1825 1947 1850">
     <span class='ocr_line' id='line_1_35' title="bbox 1902 1825 1947 1850; baseline 0 0; x_size 34; x_descenders 8.5; x_ascenders 8.5"><span class='ocrx_word' id='word_1_111' title='bbox 1902 1825 1947 1850; x_wconf 95'>OK</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_13' title="bbox 68 1882 317 1919">
    <p class='ocr_par' id='par_1_15' lang='eng' title="bbox 68 1882 317 1919">
     <span class='ocr_line' id='line_1_36' title="bbox 68 1882 317 1919; baseline -0.004 0; x_size 41.400002; x_descenders 5.4000001; x_ascenders 9"><span class='ocrx_word' id='word_1_112' title='bbox 68 1883 207 1919; x_wconf 94'>Please</span> <span class='ocrx_word' id='word_1_113' title='bbox 223 1882 317 1919; x_wconf 95'>Wait</span> 
     </span>
    </p>
   </div>
   <div class='ocr_carea' id='block_1_14' title="bbox 14 1920 1628 1984">
    <p class='ocr_par' id='par_1_16' lang='eng' title="bbox 14 1920 1628 1984">
     <span class='ocr_line' id='line_1_37' title="bbox 14 1920 1628 1984; baseline 0 13; x_size 104; x_descenders 26; x_ascenders 26"><span class='ocrx_word' id='word_1_114' title='bbox 14 1920 1628 1984; x_wconf 95'> </span> 
     </span>
    </p>
   </div>
  </div>
 </body>
</html>

**Comment by chigkim** [comment]
That's because you change the macro to display the log result. There's no error in that log. You can change back to ignore the result.
