### ISSUE TITLE
Image recognition recognises the whole screen if VoiceOver visuals are turned off, recognises image when they are turned on.

### ISSUE THREAD

**Issue by MarcoZehe** [chigkim/VOCR#12]
The title says it all: If I turn off VoiceOver visuals, as instructed by the ReadMe, image recognition will perform an OCR of the entire screen. This includes that I can navigate all the lines with CTRL+Cmd+arrows. If I turn them on, which is against the recommendation/instruction from the read me, image recognition will recognise only the image and just speak the description, not OCR the whole screen. But then, of course, window OCR is broken, because VO visuals get in the way.

This is on two M1 Macs, one running Big Sur, the other running Monterey beta.

**Comment by chigkim** [comment]
What are you trying to recognize, and are you using 
command+control+shift+w or v?

**Comment by MarcoZehe** [comment]
I was trying a result on Google image search in Safari, and was definitely using ctrl+CMD+shift+v in all attempts.

**Comment by chigkim** [comment]
Ah I see.

I'm actually planning to get rid of the image recognition feature from 
VOCR because VoiceOver itself now has better one.

VO+shift+l

Hope that helps.

**Comment by MarcoZehe** [comment]
Makes sense. Feel free to close it then.

**Comment by chigkim** [comment]
#Closed. VO has its own image recognition.
