### ISSUE TITLE
Suggestion: Allow Moving the Mouse Free-hand In Addition to From REsult to Result

### ISSUE THREAD

**Issue by BlindGuyNW** [chigkim/VOCR#14]
Hi there,

One of the programs I miss on Mac OS is a simple add-on called Golden Cursor. It basically allows, among other things, the user to move the mouse pixel by pixel across the screen. This is occasionally useful in playing games, which don't expose control information but which VOCR recognizes very well.

I suggest that some hotkeys be added to allow the mouse to move arbitrarily across the screen. This would help in cases where clicking directly on the text itself is impractical.

The other major functionality of Golden Cursor was an ability to bookmark certain parts of the screen, that is, certain pixel locations, and return to them on demand. I don't know how practical that is but it would be very nice to have as well.

I realize this isn't really an OCR problem, but the two tools are used so often together in my use case that I think of them as almost in separable.

Thanks for your work on this.

**Comment by chigkim** [comment]
You can easily make this in Keyboard Maestro. Please check out keyboardmaestro.com.
