### ISSUE TITLE
Let us Browse OCR results without Moving MOuse

### ISSUE THREAD

**Issue by BlindGuyNW** [chigkim/VOCR#15]
I find myself using applications which often pull up tooltips when the mouse is over specific parts of the screen, but the act of OCRing for them is tedious because I need to remember where the mouse was and return it to the same spot if I don’t find them on a given OCR run.

NVDA OCR, for instance, allows you to review the OCR results independently of mouse movement, with a command to route the mouse to whatever the last result was. 

THis would be useful and could perhaps be a toggle, much like the existing shortcuts for positional audio and position reset.

**Comment by diegov12** [comment]
I agree. I'm thinking there could also be some way to handle interacting with tables, since some apps require you to move the mouse to advance through a table.

**Comment by BlindGuyNW** [comment]
I'm not sure what table interaction might look like I just know that VOCR is a lot better about organizing info in columns, which I appreciate. That's probably just Visionkit working behind the scenes but still very helpful.

**Comment by chigkim** [comment]
Closed with pull #16
