### ISSUE TITLE
vocr needs update for macos ventura compatibility

### ISSUE THREAD

**Issue by vlad-a-c** [chigkim/VOCR#18]
hello.
there are some elements from some apps that are recognized just fine in the macos monterey by vocr, but on ventura they don't even show up. i met this issue in the vdj app on the login dialog where on the monterey i see the remember me checkbox and on ventura i don't. i assume there are some ocr things that were updated on ventura.
best regards

**Comment by chigkim** [comment]
It works fine on Ventura.

However, as usual updating MacOS messes up the security permission.

First uncheck and recheck everything again even though it says it's checked.

If it still doesn't work, create and log into a new user account, setup 
VOCR from scratch, and see if it works.

If it works  in the new user account, you might have to trash the whole 
security permission database in the other account.
