### ISSUE TITLE
Issue with previous and next word macros

### ISSUE THREAD

**Issue by haydendsmith** [chigkim/VOCR#2]
KM reports the following error:

/var/folders/1_/47smkf8908s0tr18sdln0rw00000gp/T/Keyboard-Maestro-Script-58F88724-FD79-4288-9428-3DBE787FA46F:225:247: execution error: Error on line 9: TypeError: undefined is not an object (evaluating 'words.length') (-2700)

**Comment by chigkim** [comment]
Were you able to execute ocr front window macro successfully before running that macros? What window were you trying to ocr? Can you just try ocr keyboard maestro editor window first?

**Comment by chigkim** [comment]
I updated the Macros. Can you download again, run import macros app, rename the macro to match your screen size, and try again? If it still fails, can you generate the report following the instruction from the end of readme? You probably have to allow import macros application from system preference under security and privacy.

**Comment by haydendsmith** [comment]
I updated the macros as requested. While focus remained in the KM Editor window, I executed "OCR Front Window 13", where 13 is the screen-size for my MacBook Pro, the following error was produced on the next word macro:

/var/folders/1_/47smkf8908s0tr18sdln0rw00000gp/T/Keyboard-Maestro-Script-63A32F70-3A8D-4BC5-95EC-69997D3DE281:225:247: execution error: Error on line 9: TypeError: undefined is not an object (evaluating 'words.length') (-2700)

**Comment by chigkim** [comment]
Can you update To the latest again and send me the log from ocr front window macro not next word macro? Follow The instruction on generating the log at the end of readme.

**Comment by haydendsmith** [comment]
Updated to the latest version as of this comment and the following output is obtained from OCR Front Window:

Desktop: 2560,1600,232
Keyboard Maestro - Keyboard Maestro Editor: 960,652
Original: 1920, 1304
Enlarged: 2483, 1686
Scale: 2.5864583333333333, 2.585889570552147
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title></title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name='ocr-system' content='tesseract 4.00.00alpha' />
  <meta name='ocr-capabilities' content='ocr_page ocr_carea ocr_par ocr_line ocrx_word'/>
</head>
<body>
  <div class='ocr_page' id='page_1' title='image "/Users/haydendsmith/Screenshot.png"; bbox 0 0 2483 1686; ppageno 0'>
  </div>
 </body>
</html>

**Comment by chigkim** [comment]
It seems like the macros is working properly.

However, either the image from screenshot is empty or Tesseract is failing.

Here are a few things to check:

1. Did you rename the macro to match your screen size?
2. Do you have screen curtain on with VoiceOver?
3. Do you use Mac Mini or Mac pro with no Monitor?

Lastly, If you go to your home folder from finder by pressing 
command+shift+h, there should be two files: Screenshot.png and 
Screenshot.hocr. Can you attach those files here?

**Comment by haydendsmith** [comment]
The second of those was the issue. Screen Curtain was enabled. The macro is now functioning perfectly.
