### ISSUE TITLE
Add option to take screenshot from the VOCR menu extras menu

### ISSUE THREAD

**Issue by mrgrieves4** [chigkim/VOCR#20]
Would it be possible to add a menu option under the VOCR menu to take the screenshot from there?

This might help with newcomers to make it more discoverable, and also those - like me - that use VOCR only occasionally who maybe are a bit forgetful and don't really need a shortcut key, or might be struggling with all the buttons needed to execute it.

I have only just started using VOCR, but it did allow mt to successfuly use an otherwise inaccessible part of an app, so I can see it being a hugely useful part of my toolbox.  So, thank you so much for this.

**Comment by chigkim** [comment]
It now lists shortcuts if you forget. Also it's customizable.

**Comment by chigkim** [comment]
https://github.com/chigkim/VOCR/releases/tag/v2.0.0-alpha.10
