### ISSUE TITLE
Translate VOCR into french and change key

### ISSUE THREAD

**Issue by math65** [chigkim/VOCR#26]
Hi, there,
I'd like to translate VOCR into French, but I don't see a . string file to do it.
Do you plan to translate the application?

And in the documentation you display keyboard shortcuts that do not correspond to the French keyboard ;)

Mathieu

**Comment by chigkim** [comment]
Unfortunately, I'm not sure how to add multi language support. Welcome contribution!

**Comment by chigkim** [comment]
Shortcuts are now customizable.

https://github.com/chigkim/VOCR/releases/tag/v2.0.0-alpha.10

Marking duplicate #25
