### ISSUE TITLE
Feature Request: Language Selection via Custom Prompt for Chat GPT in VOCR

### ISSUE THREAD

**Issue by SuperCliff** [chigkim/VOCR#27]
Hi chigkim,

Just tried out the new Chat GPT integration in VOCR – what an incredible addition! The potential for this feature is huge, and even from my brief testing, I can see how it's a game-changer.

I'd like to propose the idea of introducing a way to specify the language for Chat GPT's responses. A simple yet powerful option could be to have a text field or prompt within the settings where users can set a standard prompt with the desired language. For example, I would write "Norwegian" to receive responses in my native tongue.

Looking ahead, this prompt-based approach could bring even more value, allowing users to not only set the language but also include instructions on the kind of response they need – like "Give me a high-level overview," or "Please provide detailed descriptions of all interactive elements."

While the primary goal is to enable multilingual support, this flexibility could also pave the way for personalized content analysis – a bonus that might favor a prompt solution over a simple language option.

Seeing how quickly VOCR evolves, adding this feature could make the app an even more indispensable tool for international users, including those of us using VoiceOver.

Appreciate the work you're doing and looking forward to future updates!

All the best,

**Comment by chigkim** [comment]
If you use Ask GPT about VOCursor (command+control+shift+a), you can edit the prompt for whatever you like.

**Comment by SuperCliff** [comment]
Hi there!

Ahh, that’s a nice feature! 👍🏻 
But that doesn’t do anything with the labels and screen elements when navigating using Ctrl-Cmd-Shift-arrow keys after analysing with GpT. I tried now with a Peugeot Update app that has always been messy in regards to accessibility, and although the apps interface in my case is localised to Norwegian, the GpT analyse translates everything back to english when trying to navigate it. If I do the normal OCR scan with W instead of E, I can navigate what’s actually there instead of having it translated back to english.
Is it possible to do anything about this?

Regards 
Cliff
